[package]
name = "ecdh"
type = "bin"
authors = [""]
compiler_version = "0.10.5"

# [dependencies]
noir_bigint = { tag = "v0.1.0", git = "https://github.com/shuklaayush/noir-bigint" }
biguint = { tag = "v0.1.0", git = "https://github.com/shuklaayush/noir-bigint" }