[package]
name = "noir-ecdh"
type = "lib"
authors = [""]
compiler_version = ">=0.18.0"

# [dependencies]
noir_bigint = { tag = "v0.1.0", git = "https://github.com/shuklaayush/noir-bigint" }
biguint = { tag = "v0.1.0", git = "https://github.com/shuklaayush/noir-bigint" }
